name: authorization
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  firebase_database: ^10.5.5
  get_it: ^7.7.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  auto_route: ^8.1.3
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  talker_flutter: ^4.2.0
  talker_bloc_logger: ^4.2.0
  talker_dio_logger: ^4.2.0
  email_validator: ^2.1.17
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  gif_view: ^0.4.3
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  fl_chart: ^0.68.0

  image_picker: ^1.1.1
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.3
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1 
  build_runner: ^2.4.9
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/
    - assets/json/


  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
