name: authorization
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  firebase_storage: ^11.5.5
  firebase_database: ^10.3.8
  get_it: ^7.6.4
  dio: ^5.4.0
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  talker_flutter: ^3.5.7
  talker_bloc_logger: ^2.3.3
  talker_dio_logger: ^2.3.4
  email_validator: ^2.1.17
  dots_indicator: ^3.0.0
  percent_indicator: ^4.2.3
  gif_view: ^0.4.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1 
  build_runner: ^2.4.7
  
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/
    - assets/json/


  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700
